export const providers = [
  {
    name: "Resend",
    key: "resend",
    importPath: "email-sdk/resend",
    docs: "/docs/adapters/resend",
    website: "https://resend.com",
    logo: "https://cdn.simpleicons.org/resend",
    sidebarLogo: "https://cdn.simpleicons.org/resend/white",
    category: "Popular APIs",
  },
  {
    name: "Postmark",
    key: "postmark",
    importPath: "email-sdk/postmark",
    docs: "/docs/adapters/postmark",
    website: "https://postmarkapp.com",
    logo: "https://www.google.com/s2/favicons?domain=postmarkapp.com&sz=64",
    category: "Popular APIs",
  },
  {
    name: "SendGrid",
    key: "sendgrid",
    importPath: "email-sdk/sendgrid",
    docs: "/docs/adapters/sendgrid",
    website: "https://sendgrid.com",
    logo: "https://www.google.com/s2/favicons?domain=sendgrid.com&sz=64",
    category: "Popular APIs",
  },
  {
    name: "Mailgun",
    key: "mailgun",
    importPath: "email-sdk/mailgun",
    docs: "/docs/adapters/mailgun",
    website: "https://www.mailgun.com",
    logo: "https://cdn.simpleicons.org/mailgun",
    category: "Popular APIs",
  },
  {
    name: "MailerSend",
    key: "mailersend",
    importPath: "email-sdk/mailersend",
    docs: "/docs/adapters/mailersend",
    website: "https://www.mailersend.com",
    logo: "https://www.google.com/s2/favicons?domain=mailersend.com&sz=64",
    category: "Popular APIs",
  },
  {
    name: "Brevo",
    key: "brevo",
    importPath: "email-sdk/brevo",
    docs: "/docs/adapters/brevo",
    website: "https://www.brevo.com",
    logo: "https://cdn.simpleicons.org/brevo",
    category: "Popular APIs",
  },
  {
    name: "Mailchimp Transactional",
    key: "mailchimp",
    importPath: "email-sdk/mailchimp",
    docs: "/docs/adapters/mailchimp",
    website: "https://mailchimp.com/features/transactional-email",
    logo: "https://cdn.simpleicons.org/mailchimp",
    category: "Popular APIs",
  },
  {
    name: "SparkPost",
    key: "sparkpost",
    importPath: "email-sdk/sparkpost",
    docs: "/docs/adapters/sparkpost",
    website: "https://www.sparkpost.com",
    logo: "https://cdn.simpleicons.org/sparkpost",
    category: "Infrastructure",
  },
  {
    name: "Mailtrap",
    key: "mailtrap",
    importPath: "email-sdk/mailtrap",
    docs: "/docs/adapters/mailtrap",
    website: "https://mailtrap.io",
    logo: "https://cdn.simpleicons.org/mailtrap",
    category: "Infrastructure",
  },
  {
    name: "Scaleway",
    key: "scaleway",
    importPath: "email-sdk/scaleway",
    docs: "/docs/adapters/scaleway",
    website: "https://www.scaleway.com/en/transactional-email-tem",
    logo: "https://cdn.simpleicons.org/scaleway",
    category: "Infrastructure",
  },
  {
    name: "ZeptoMail",
    key: "zeptomail",
    importPath: "email-sdk/zeptomail",
    docs: "/docs/adapters/zeptomail",
    website: "https://www.zoho.com/zeptomail",
    logo: "https://cdn.simpleicons.org/zoho",
    category: "Infrastructure",
  },
  {
    name: "MailPace",
    key: "mailpace",
    importPath: "email-sdk/mailpace",
    docs: "/docs/adapters/mailpace",
    website: "https://mailpace.com",
    logo: "https://www.google.com/s2/favicons?domain=mailpace.com&sz=64",
    category: "Infrastructure",
  },
  {
    name: "Loops",
    key: "loops",
    importPath: "email-sdk/loops",
    docs: "/docs/adapters/loops",
    website: "https://loops.so",
    logo: "https://cdn.simpleicons.org/loops",
    category: "Product-led",
  },
  {
    name: "Plunk",
    key: "plunk",
    importPath: "email-sdk/plunk",
    docs: "/docs/adapters/plunk",
    website: "https://www.useplunk.com",
    logo: "https://www.google.com/s2/favicons?domain=useplunk.com&sz=64",
    category: "Product-led",
  },
  {
    name: "SMTP",
    key: "smtp",
    importPath: "email-sdk/smtp",
    docs: "/docs/adapters/smtp",
    website: "https://datatracker.ietf.org/doc/html/rfc5321",
    logo: "",
    category: "Transport",
  },
] as const;

export type Provider = (typeof providers)[number];
