export { createEmailClient } from "./core.js";
export {
  EmailProviderError,
  EmailProviderNotFoundError,
  EmailSdkError,
  EmailValidationError,
  isRetryableEmailError,
} from "./errors.js";
export type {
  EmailAddress,
  EmailAttachment,
  EmailAfterSendEvent,
  EmailBeforeSendEvent,
  EmailBeforeSendResult,
  EmailClient,
  EmailClientOptions,
  EmailErrorEvent,
  EmailHeader,
  EmailHooks,
  EmailMessage,
  EmailPlugin,
  EmailPluginClientExtension,
  EmailPluginClientExtensions,
  EmailPluginContext,
  EmailProvider,
  EmailProviderContext,
  EmailProviderResponse,
  EmailRetryConfig,
  EmailSendMiddleware,
  EmailTag,
  SendBatchItem,
  SendBatchResult,
  SendOptions,
  UnionToIntersection,
} from "./types.js";
